# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Study Notes
tagline:             'A Jekyll theme'
description: > # this means to ignore newlines until "baseurl:"
Thanks for Github that sets the platform where I can embrace new techonology on.
Such as Java , C/C++ ,Linux C ,J EE/SE , Data Structure.
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              HeartQ
  email:             cyrusyang@yeah.net

# Custom vars
version:             1.0.0
